# Generated by Django 5.2.4 on 2025-07-19 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('Email', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55)),
                ('rating', models.CharField(max_length=5)),
                ('remark', models.TextField(default='')),
                ('date', models.DateField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
