# Generated by Django 5.2.4 on 2025-07-19 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=13)),
                ('question', models.TextField()),
                ('date', models.DateField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
