# Generated by Django 5.2.4 on 2025-07-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_pic',
            field=models.CharField(default='', max_length=255),
        ),
    ]
