# Generated by Django 5.2.4 on 2025-07-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0005_reg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reg',
            new_name='User',
        ),
    ]
