# Generated by Django 5.2.4 on 2025-07-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0006_rename_reg_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopowner',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=60, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=13)),
                ('pic_name', models.FileField(default='', upload_to='owner_pic/')),
            ],
        ),
    ]
