# Generated by Django 5.2.4 on 2025-07-27 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0007_shopowner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDetail',
            fields=[
                ('shop_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('location_lat', models.CharField(max_length=100)),
                ('location_long', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField(default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='medi_app.shopowner')),
            ],
        ),
    ]
