# Generated by Django 5.2.4 on 2025-08-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0008_shopdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('user_whatsapp', models.CharField(max_length=13)),
                ('medicine_name', models.CharField(max_length=100)),
                ('refer_doctor_name', models.CharField(max_length=100, null=True)),
                ('user_message', models.TextField(default='', null=True)),
                ('medicine_status', models.CharField(choices=[('REQUESTED', 'Requested'), ('RECEIVED', 'Medicine Received'), ('CANCELLED', 'Request Cancelled')], default='REQUESTED', max_length=30)),
            ],
        ),
    ]
