# Generated by Django 5.2.4 on 2025-09-16 11:41

import django.core.validators
import medi_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0009_medicinerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[medi_app.models.validate_gmail])),
                ('profile_image', models.FileField(upload_to='profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
            ],
        ),
    ]
