# Generated by Django 5.2.4 on 2025-09-17 06:16

import medi_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0015_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=60, validators=[medi_app.models.validate_gmail]),
        ),
    ]
