# Generated by Django 5.2.4 on 2025-09-17 06:19

import medi_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0016_user_id_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=60, primary_key=True, serialize=False, validators=[medi_app.models.validate_gmail]),
        ),
    ]
