# Generated by Django 5.2.4 on 2025-09-17 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0017_remove_user_id_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pic_name',
            field=models.FileField(blank=True, default='', null=True, upload_to='user_pic/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
