# Generated by Django 5.2.4 on 2025-09-17 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medi_app', '0018_alter_user_pic_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
